# Generated by Django 4.2.29 on 2026-03-06 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.BinaryField(help_text='Dữ liệu vector khuôn mặt được mã hóa', verbose_name='Vector đặc trưng khuôn mặt')),
                ('image', models.ImageField(blank=True, null=True, upload_to='face_crops/%Y/%m/%d/', verbose_name='Ảnh khuôn mặt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_embeddings', to='employees.employee', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Dữ liệu khuôn mặt',
                'verbose_name_plural': 'Dữ liệu khuôn mặt',
                'db_table': 'face_embeddings',
            },
        ),
    ]
