# Generated by Django 4.2.29 on 2026-03-06 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('face_recognition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian quét')),
                ('confidence', models.FloatField(default=0.0, verbose_name='Độ tin cậy')),
                ('image', models.ImageField(blank=True, null=True, upload_to='face_logs/%Y/%m/%d/', verbose_name='Ảnh')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_logs', to='employees.employee', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Lịch sử nhận diện',
                'verbose_name_plural': 'Lịch sử nhận diện',
                'db_table': 'face_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
