# Generated by Django 4.2.29 on 2026-04-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition', '0002_facelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, verbose_name='ID Người dùng')),
                ('image_count', models.IntegerField(default=0, verbose_name='Số ảnh đã đăng ký')),
                ('status', models.CharField(choices=[('pending', 'Đang chờ'), ('completed', 'Hoàn tất'), ('failed', 'Thất bại')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name': 'Đăng ký khuôn mặt',
                'verbose_name_plural': 'Đăng ký khuôn mặt',
                'db_table': 'face_registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
