# Generated by Django 4.2.30 on 2026-06-03 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('face_recognition', '0005_postgres_vector_registration_metadata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faceembedding',
            options={'verbose_name': 'Du lieu khuon mat', 'verbose_name_plural': 'Du lieu khuon mat'},
        ),
        migrations.AlterModelOptions(
            name='facelog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Lich su nhan dien', 'verbose_name_plural': 'Lich su nhan dien'},
        ),
        migrations.AlterModelOptions(
            name='faceregistration',
            options={'ordering': ['-created_at'], 'verbose_name': 'Dang ky khuon mat', 'verbose_name_plural': 'Dang ky khuon mat'},
        ),
        migrations.AlterField(
            model_name='faceembedding',
            name='cloudinary_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Link anh khuon mat Cloudinary'),
        ),
        migrations.AlterField(
            model_name='faceembedding',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngay tao'),
        ),
        migrations.AlterField(
            model_name='faceembedding',
            name='embedding',
            field=models.BinaryField(blank=True, help_text='Du lieu vector khuon mat dang bytes de tuong thich code cu', null=True, verbose_name='Vector khuon mat binary'),
        ),
        migrations.AlterField(
            model_name='faceembedding',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_embeddings', to='employees.employee', verbose_name='Nhan vien'),
        ),
        migrations.AlterField(
            model_name='faceembedding',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='face_crops/%Y/%m/%d/', verbose_name='Anh khuon mat'),
        ),
        migrations.AlterField(
            model_name='facelog',
            name='confidence',
            field=models.FloatField(default=0.0, verbose_name='Do tin cay'),
        ),
        migrations.AlterField(
            model_name='facelog',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_logs', to='employees.employee', verbose_name='Nhan vien'),
        ),
        migrations.AlterField(
            model_name='facelog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='face_logs/%Y/%m/%d/', verbose_name='Anh'),
        ),
        migrations.AlterField(
            model_name='facelog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thoi gian quet'),
        ),
        migrations.AlterField(
            model_name='faceregistration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thoi gian tao'),
        ),
        migrations.AlterField(
            model_name='faceregistration',
            name='image_count',
            field=models.IntegerField(default=0, verbose_name='So anh da dang ky'),
        ),
        migrations.AlterField(
            model_name='faceregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'Dang cho'), ('completed', 'Hoan tat'), ('failed', 'That bai')], default='pending', max_length=20, verbose_name='Trang thai'),
        ),
        migrations.AlterField(
            model_name='faceregistration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Thoi gian cap nhat'),
        ),
        migrations.AlterField(
            model_name='faceregistration',
            name='user_id',
            field=models.CharField(max_length=255, verbose_name='ID nguoi dung'),
        ),
    ]
