# Generated by Django 4.2.30 on 2026-06-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition', '0006_alter_faceembedding_options_alter_facelog_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faceembedding',
            name='embedding',
        ),
        migrations.RemoveField(
            model_name='faceembedding',
            name='embedding_vector',
        ),
        migrations.AddField(
            model_name='faceembedding',
            name='chroma_collection',
            field=models.CharField(blank=True, default='face_embeddings', max_length=100, verbose_name='Collection ChromaDB'),
        ),
        migrations.AddField(
            model_name='faceembedding',
            name='chroma_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID vector trong ChromaDB'),
        ),
    ]
