# Generated by Codex on 2026-06-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition', '0007_remove_faceembedding_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceembedding',
            name='embedding',
            field=models.BinaryField(
                blank=True,
                help_text='Du lieu vector khuon mat luu truc tiep trong PostgreSQL',
                null=True,
                verbose_name='Vector khuon mat binary',
            ),
        ),
    ]
