# Generated by Codex on 2026-06-05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition', '0008_faceembedding_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faceembedding',
            name='chroma_collection',
        ),
        migrations.RemoveField(
            model_name='faceembedding',
            name='chroma_id',
        ),
    ]
