# Generated by Django 4.2.29 on 2026-03-04 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ngày')),
                ('check_in', models.DateTimeField(blank=True, null=True, verbose_name='Giờ vào')),
                ('check_out', models.DateTimeField(blank=True, null=True, verbose_name='Giờ ra')),
                ('status', models.CharField(choices=[('present', 'Có mặt'), ('late', 'Đi trễ'), ('absent', 'Vắng'), ('leave', 'Nghỉ phép')], default='present', max_length=10, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, default='', verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='employees.employee', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Bản chấm công',
                'verbose_name_plural': 'Bản chấm công',
                'db_table': 'attendance_logs',
                'ordering': ['-date', '-check_in'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
