# Generated by Django 4.2.30 on 2026-06-10 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ngày tăng ca')),
                ('planned_start_time', models.TimeField(verbose_name='Giờ bắt đầu')),
                ('planned_end_time', models.TimeField(verbose_name='Giờ kết thúc')),
                ('planned_hours', models.DecimalField(decimal_places=1, editable=False, max_digits=3, verbose_name='Số giờ dự kiến')),
                ('overtime_rate', models.DecimalField(decimal_places=1, editable=False, max_digits=2, verbose_name='Hệ số tăng ca')),
                ('reason', models.TextField(verbose_name='Lý do')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=10, verbose_name='Trạng thái')),
                ('rejection_reason', models.TextField(blank=True, default='', verbose_name='Lý do từ chối')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian duyệt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_requests', to='employees.employee', verbose_name='Nhân viên')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_overtime_requests', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt')),
            ],
            options={
                'verbose_name': 'Đơn tăng ca',
                'verbose_name_plural': 'Đơn tăng ca',
                'db_table': 'overtime_requests',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
