# Generated by Django 4.2.30 on 2026-06-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtimerequest',
            name='reason',
            field=models.TextField(blank=True, default='', verbose_name='Lý do'),
        ),
    ]
