# Generated by Django 4.2.29 on 2026-03-04 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên ca')),
                ('start_time', models.TimeField(verbose_name='Giờ bắt đầu')),
                ('end_time', models.TimeField(verbose_name='Giờ kết thúc')),
                ('late_threshold', models.PositiveIntegerField(default=15, help_text='Số phút cho phép đến trễ trước khi bị tính trễ.', verbose_name='Ngưỡng đi trễ (phút)')),
            ],
            options={
                'verbose_name': 'Ca làm việc',
                'verbose_name_plural': 'Ca làm việc',
                'db_table': 'shifts',
            },
        ),
        migrations.CreateModel(
            name='EmployeeShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(verbose_name='Ngày hiệu lực')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_shifts', to='employees.employee', verbose_name='Nhân viên')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_shifts', to='shifts.shift', verbose_name='Ca làm việc')),
            ],
            options={
                'verbose_name': 'Phân ca',
                'verbose_name_plural': 'Phân ca',
                'db_table': 'employee_shifts',
                'ordering': ['-effective_date'],
            },
        ),
    ]
